# Generated by Django 4.2.4 on 2023-08-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exemen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('date_test', models.DateField()),
                ('no_registre', models.IntegerField()),
                ('HIV_test', models.CharField(max_length=150)),
                ('HBS_test', models.CharField(max_length=150)),
                ('HCV_test', models.CharField(max_length=150)),
                ('BW_test', models.CharField(max_length=150)),
                ('TOXOPLASME_test', models.CharField(max_length=150)),
                ('RUBIOLE_test', models.CharField(max_length=150)),
                ('observation', models.CharField(max_length=500)),
            ],
        ),
    ]
